In [1]:
import numpy as np
from scipy import io, integrate, linalg, signal
from scipy.sparse.linalg import cg, eigs

In [2]:
a = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
np.ndim(a)

2

In [4]:
np.size(a) 


6

In [5]:
np.shape(a)

(2, 3)

In [6]:
n = 2
a.shape[n-1]

3

In [7]:
A = np.eye(2) * 2
B = np.zeros((2, 3))
C = np.ones((3, 2))
D = np.eye(3) * 3
np.block([[A, B],[C, D]])

#np.block([[a, b], [c, d]])

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [8]:
a = np.block([[A, B],[C, D]])
a[-1]

array([1., 1., 0., 0., 3.])

In [9]:
a[1, 4]

0.0

In [10]:
a[1]

array([0., 2., 0., 0., 0.])

In [11]:
a[0: 5]

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [12]:
a[-5: ]

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3.]])

In [13]:
a = np.block([[A, B, A, B], [C, D, C, D]])
a

array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0., 1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.]])

In [14]:
np.shape(a)

(5, 10)

In [15]:
a[0:3, 4:9]

array([[0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 1., 1., 3., 0.]])

In [16]:
a[np.ix_([1, 3, 4], [0, 2])]

array([[0., 0.],
       [1., 0.],
       [1., 0.]])

In [17]:
a[2:21:2,:]

array([[1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.]])

In [18]:
a[::2, :]


array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.]])

In [19]:
a[::-1,:]

array([[1., 1., 0., 0., 3., 1., 1., 0., 0., 3.],
       [1., 1., 0., 3., 0., 1., 1., 0., 3., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [0., 2., 0., 0., 0., 0., 2., 0., 0., 0.],
       [2., 0., 0., 0., 0., 2., 0., 0., 0., 0.]])

In [20]:
a[np.r_[:len(a),0]]

array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0., 1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.],
       [2., 0., 0., 0., 0., 2., 0., 0., 0., 0.]])

In [21]:
a.transpose() 

array([[2., 0., 1., 1., 1.],
       [0., 2., 1., 1., 1.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.],
       [2., 0., 1., 1., 1.],
       [0., 2., 1., 1., 1.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [22]:
a.conj().transpose()

array([[2., 0., 1., 1., 1.],
       [0., 2., 1., 1., 1.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.],
       [2., 0., 1., 1., 1.],
       [0., 2., 1., 1., 1.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [23]:
b = a.transpose() 

In [24]:
a @ b

array([[ 8.,  0.,  4.,  4.,  4.],
       [ 0.,  8.,  4.,  4.,  4.],
       [ 4.,  4., 22.,  4.,  4.],
       [ 4.,  4.,  4., 22.,  4.],
       [ 4.,  4.,  4.,  4., 22.]])

In [25]:
b = a - 1

In [26]:
a * b

array([[ 2., -0., -0., -0., -0.,  2., -0., -0., -0., -0.],
       [-0.,  2., -0., -0., -0., -0.,  2., -0., -0., -0.],
       [ 0.,  0.,  6., -0., -0.,  0.,  0.,  6., -0., -0.],
       [ 0.,  0., -0.,  6., -0.,  0.,  0., -0.,  6., -0.],
       [ 0.,  0., -0., -0.,  6.,  0.,  0., -0., -0.,  6.]])

In [27]:
a/b

/var/folders/p9/5m4c57v11m51yp133jvxcb_40000gn/T/ipykernel_19777/1348051284.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/b


array([[ 2. , -0. , -0. , -0. , -0. ,  2. , -0. , -0. , -0. , -0. ],
       [-0. ,  2. , -0. , -0. , -0. , -0. ,  2. , -0. , -0. , -0. ],
       [ inf,  inf,  1.5, -0. , -0. ,  inf,  inf,  1.5, -0. , -0. ],
       [ inf,  inf, -0. ,  1.5, -0. ,  inf,  inf, -0. ,  1.5, -0. ],
       [ inf,  inf, -0. , -0. ,  1.5,  inf,  inf, -0. , -0. ,  1.5]])

In [28]:
a**3

array([[ 8.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.],
       [ 0.,  8.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.],
       [ 1.,  1., 27.,  0.,  0.,  1.,  1., 27.,  0.,  0.],
       [ 1.,  1.,  0., 27.,  0.,  1.,  1.,  0., 27.,  0.],
       [ 1.,  1.,  0.,  0., 27.,  1.,  1.,  0.,  0., 27.]])

In [29]:
(a > 0.5)

array([[ True, False, False, False, False,  True, False, False, False,
        False],
       [False,  True, False, False, False, False,  True, False, False,
        False],
       [ True,  True,  True, False, False,  True,  True,  True, False,
        False],
       [ True,  True, False,  True, False,  True,  True, False,  True,
        False],
       [ True,  True, False, False,  True,  True,  True, False, False,
         True]])

In [30]:
a

array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0., 1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.]])

In [38]:
v = a[0:1, :]
v

array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.]])

In [39]:
a[:,np.nonzero(v > 0.5)[0]]

array([[2., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
a[a < 0.5]=0

In [36]:
a * (a > 0.5)

array([[2., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 2., 0., 0., 0.],
       [1., 1., 3., 0., 0., 1., 1., 3., 0., 0.],
       [1., 1., 0., 3., 0., 1., 1., 0., 3., 0.],
       [1., 1., 0., 0., 3., 1., 1., 0., 0., 3.]])

In [37]:
a[:] = 3

In [38]:
x = a
y = x.copy()

In [39]:
np.arange(1., 11.)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
np.arange(10.) 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
np.arange(1.,11.)[:, np.newaxis]

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

In [42]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [44]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.diag(a)

array([3., 3., 3., 3., 3.])

In [47]:
np.diag(v, 0)

array([3., 3., 4., 4., 4.])

In [48]:
np.linspace(1,3,4)

array([1.        , 1.66666667, 2.33333333, 3.        ])

In [49]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [50]:
from numpy.random import default_rng
#rng = default_rng(42)
#rng.random(3, 4)

In [51]:
np.mgrid[0:9.,0:6.]

array([[[0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]],

       [[0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.],
        [0., 1., 2., 3., 4., 5.]]])

In [52]:
#ogrid[0:9.,0:6.] 
np.ix_(np.r_[0:9.],np.r_[0:6.])

(array([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]]),
 array([[0., 1., 2., 3., 4., 5.]]))

In [53]:
np.meshgrid([1,2,4],[2,4,5])

[array([[1, 2, 4],
        [1, 2, 4],
        [1, 2, 4]]),
 array([[2, 2, 2],
        [4, 4, 4],
        [5, 5, 5]])]

In [54]:
np.ix_([1,2,4],[2,4,5])

(array([[1],
        [2],
        [4]]),
 array([[2, 4, 5]]))

In [55]:
m = 3
np.tile(a, (m, n))

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
        3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.

In [56]:
np.concatenate((a,b),1)

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  1., -1., -1.,
        -1., -1.,  1., -1., -1., -1., -1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3., -1.,  1., -1.,
        -1., -1., -1.,  1., -1., -1., -1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  0.,  0.,  2.,
        -1., -1.,  0.,  0.,  2., -1., -1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  0.,  0., -1.,
         2., -1.,  0.,  0., -1.,  2., -1.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  0.,  0., -1.,
        -1.,  2.,  0.,  0., -1., -1.,  2.]])

In [57]:
np.concatenate((a,b))

array([[ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 1., -1., -1., -1., -1.,  1., -1., -1., -1., -1.],
       [-1.,  1., -1., -1., -1., -1.,  1., -1., -1., -1.],
       [ 0.,  0.,  2., -1., -1.,  0.,  0.,  2., -1., -1.],
       [ 0.,  0., -1.,  2., -1.,  0.,  0., -1.,  2., -1.],
       [ 0.,  0., -1., -1.,  2.,  0.,  0., -1., -1.,  2.]])

In [58]:
a.max()

3.0

In [59]:
a.max(0)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [60]:
a.max(1)

array([3., 3., 3., 3., 3.])

In [61]:
np.maximum(a, b)

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [62]:
v = v[0:5, 0:5]

In [63]:
np.sqrt(v @ v)

array([[4.        , 3.46410162, 3.16227766, 3.16227766, 3.16227766],
       [3.46410162, 4.        , 3.16227766, 3.16227766, 3.16227766],
       [4.47213595, 4.47213595, 4.69041576, 3.60555128, 3.60555128],
       [4.47213595, 4.47213595, 3.60555128, 4.69041576, 3.60555128],
       [4.47213595, 4.47213595, 3.60555128, 3.60555128, 4.69041576]])

In [64]:
np.logical_or(a,b)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [65]:
a = np.array([2, 5, 255])
b = np.array([3, 14, 16])

a & b

array([ 2,  4, 16])

In [66]:
a | b

array([  3,  15, 255])

In [67]:
a = np.array([[1., 2.], [3., 4.]])
linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [68]:
linalg.pinv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [69]:
np.linalg.matrix_rank(a)

2

In [70]:
b = np.array([1, 2])
linalg.solve(a, b)

array([0. , 0.5])

In [71]:
U, S, Vh = linalg.svd(a); 
V = Vh.T

In [72]:
#a = np.array([[1,-2j],[2j,5]])
a = np.array([[0., -1.], [1., 0.]])
b = np.array([[0., 1.], [1., 1.]])

linalg.cholesky(np.matrix(A))

array([[1.41421356, 0.        ],
       [0.        , 1.41421356]])

In [73]:
D,V = linalg.eig(a)
D,V

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [74]:
D,V = linalg.eig(a, b)
D,V

(array([ 1.+0.j, -1.+0.j]),
 array([[ 1.        , -0.4472136 ],
        [ 0.        ,  0.89442719]]))

In [75]:
D,V = eigs(a, k=3)
D,V

/Users/yihanhong/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py:1266: RuntimeWarning: k >= N - 1 for N * N square matrix. Attempting to use scipy.linalg.eig instead.
  warnings.warn("k >= N - 1 for N * N square matrix. "


(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [76]:
Q,R = linalg.qr(a)
Q,R

(array([[ 0., -1.],
        [-1.,  0.]]),
 array([[-1.,  0.],
        [ 0.,  1.]]))

In [77]:
P,L,U = linalg.lu(a) #where a == P@L@U
P,L,U

(array([[0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[ 1.,  0.],
        [ 0., -1.]]))

In [78]:
np.fft.fft(a)

array([[-1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j]])

In [79]:
np.fft.ifft(a)

array([[-0.5+0.j,  0.5+0.j],
       [ 0.5+0.j,  0.5+0.j]])

In [80]:
np.sort(a) #or a.sort(axis=0)

array([[-1.,  0.],
       [ 0.,  1.]])

In [81]:
np.sort(a, axis=1) #or a.sort(axis=1)

array([[-1.,  0.],
       [ 0.,  1.]])

In [82]:
I = np.argsort(a[:, 0]); 
I

array([0, 1])

In [83]:
b = a[I,:]
b

array([[ 0., -1.],
       [ 1.,  0.]])

In [84]:
Z = np.array([[ 0.,  1.],
       [ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.]])
y = np.array([-1, 0.2, 0.9, 2.1])
x = linalg.lstsq(Z, y)
x

(array([ 1.  , -0.95]),
 0.049999999999999906,
 2,
 array([4.10003045, 1.09075677]))

In [85]:
x = np.linspace(0, 10, 20, endpoint=False)
np.linspace(0, 10, 20, endpoint=False)
y = np.cos(-x**2/6.0)
f = signal.resample(y, 100)
f

array([ 1.        ,  1.23283311,  1.31727019,  1.27302765,  1.14740269,
        0.99913207,  0.88078847,  0.82497964,  0.83806509,  0.90249922,
        0.98614323,  1.05486   ,  1.08402435,  1.06536954,  1.00747904,
        0.93050762,  0.85758366,  0.80620995,  0.78263328,  0.78081837,
        0.78588726,  0.78033048,  0.75048699,  0.69094819,  0.60552319,
        0.50478221,  0.40143727,  0.30548407,  0.22092394,  0.14511765,
        0.0707372 , -0.01068719, -0.10512733, -0.21370903, -0.33240564,
       -0.45366208, -0.56910426, -0.67215691, -0.75955883, -0.83131707,
       -0.88932657, -0.93540864, -0.9696874 , -0.98998822, -0.9924354 ,
       -0.97288395, -0.92847886, -0.85863231, -0.76502853, -0.65074937,
       -0.51903563, -0.37236513, -0.21236454, -0.04065068,  0.13978552,
        0.3233596 ,  0.50154373,  0.66375109,  0.79927642,  0.89960584,
        0.96017029,  0.98077748,  0.96447814,  0.91530208,  0.8358487 ,
        0.7258814 ,  0.58274561,  0.40370101,  0.18940426, -0.05

In [86]:
np.unique(a)

array([-1.,  0.,  1.])

In [87]:
a.squeeze()

array([[ 0., -1.],
       [ 1.,  0.]])